[project]
name = "ai-manager"
version = "0.1.0"
description = "AI manager agent for LangGraph Studio"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "pydantic-settings",
    "pydantic",
    "SQLAlchemy",
    "redis",
    "pytest",
    "pytest-mock",
    "aio-pika",
    "langchain-ollama",
    "langgraph",
    "langchain",
    "langchain-core",
    "langchain-community",
    "ipython",
    "langgraph-checkpoint-postgres",
    "psycopg-binary",
    "langchain_openai",
    "nemoguardrails",
    "langchain-groq",
    "mem0ai",
    "sentence-transformers",
    "chromadb",
    "pypdf",
    "langchain-classic",
    "unstructured",
    "unstructured[pdf]",
    "faiss-cpu",
    "langchain_postgres",
    "langchain_huggingface",
    "langgraph-cli[inmem]",
]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"